'use strict';

const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const test = require('node:test');
const {
  automaticSlug,
  validateDatabaseSchema,
  validatePublishedPages,
} = require('./content-schema');
const {
  buildSnapshot,
  createManifest,
  downloadNotionImage,
  escapeMarkdownText,
  generateSmartExcerpt,
  normalizeGeneratedExcerpt,
  resolveContentDir,
  richTextToMarkdown,
  sanitizeUrl,
  serializeFrontmatter,
  writeSnapshot,
} = require('./sync-notion');

function databaseFixture() {
  return {
    properties: {
      '名称': { type: 'title', title: {} },
      Slug: { type: 'rich_text', rich_text: {} },
      Status: { type: 'select', select: { options: [{ name: 'Draft' }, { name: 'Published' }] } },
      Date: { type: 'date', date: {} },
      Excerpt: { type: 'rich_text', rich_text: {} },
      Group: { type: 'select', select: { options: [{ name: 'tech' }, { name: 'notes' }] } },
      Tags: { type: 'multi_select', multi_select: { options: [] } },
      Cover: { type: 'files', files: {} },
      Aliases: { type: 'multi_select', multi_select: { options: [] } },
    },
  };
}

function richText(value) {
  return [{ plain_text: value, annotations: {} }];
}

function pageFixture(overrides = {}) {
  const id = overrides.id || 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa';
  const value = (name, fallback) => Object.hasOwn(overrides, name) ? overrides[name] : fallback;
  const slug = value('slug', 'safe-article');
  return {
    id,
    created_time: value('createdTime', '2026-07-18T08:00:00.000Z'),
    last_edited_time: '2026-07-19T08:00:00.000Z',
    cover: null,
    properties: {
      '名称': { type: 'title', title: richText(overrides.title || 'Safe <Article>') },
      Slug: { type: 'rich_text', rich_text: richText(slug) },
      Status: { type: 'select', select: { name: overrides.status || 'Published' } },
      Date: { type: 'date', date: { start: value('date', '2026-07-19') } },
      Excerpt: { type: 'rich_text', rich_text: richText(value('excerpt', 'Summary')) },
      Group: { type: 'select', select: { name: value('group', 'tech') } },
      Tags: { type: 'multi_select', multi_select: [{ name: 'node' }, { name: 'node' }] },
      Cover: { type: 'files', files: [] },
      Aliases: {
        type: 'multi_select',
        multi_select: (overrides.aliases || []).map((name) => ({ name })),
      },
    },
  };
}

test('database and published page use one shared schema contract', () => {
  const databaseResult = validateDatabaseSchema(databaseFixture(), { groupAllowlist: ['tech', 'notes'] });
  assert.deepEqual(databaseResult.errors, []);

  const pageResult = validatePublishedPages([
    pageFixture({ aliases: ['old-safe-article', 'safe-article'] }),
  ], { groupAllowlist: ['tech', 'notes'] });
  assert.deepEqual(pageResult.errors, []);
  assert.deepEqual(pageResult.articles[0].aliases, ['old-safe-article']);
  assert.deepEqual(pageResult.articles[0].tags, ['node']);
});

test('only title and Published status are required for article metadata', () => {
  const minimalDatabase = databaseFixture();
  ['Slug', 'Date', 'Excerpt', 'Group', 'Tags', 'Cover', 'Aliases'].forEach((name) => {
    delete minimalDatabase.properties[name];
  });
  assert.deepEqual(validateDatabaseSchema(minimalDatabase).errors, []);

  const page = pageFixture({ slug: '', date: '', excerpt: '', group: '' });
  const result = validatePublishedPages([page]);
  assert.deepEqual(result.errors, []);
  assert.equal(result.articles[0].slug, automaticSlug(page.id));
  assert.equal(result.articles[0].date, '2026-07-18');
  assert.equal(result.articles[0].excerpt, '');
  assert.equal(result.articles[0].group, 'notes');
});

test('empty excerpt is generated by the model instead of copied from the first paragraph', async () => {
  let requestBody;
  const excerpt = await generateSmartExcerpt({
    title: '自动化工具小结',
    body: '这是正文第一段，不应该被直接复制成摘要。',
  }, {
    token: 'test-token',
    fetchImpl: async (_url, init) => {
      requestBody = JSON.parse(init.body);
      return {
        ok: true,
        json: async () => ({
          choices: [{ message: { content: '摘要：通过自动化工具收敛重复验收流程，重点分析实际落地中的取舍、局限与对团队效率的价值。' } }],
        }),
      };
    },
  });
  assert.match(requestBody.messages[1].content, /不应该被直接复制/);
  assert.doesNotMatch(excerpt, /^摘要/);
  assert.doesNotMatch(excerpt, /^这是正文第一段/);
  assert.equal(normalizeGeneratedExcerpt('“稳定摘要内容”'), '稳定摘要内容');
});

test('published metadata validation collects errors across all pages', () => {
  const result = validatePublishedPages([
    pageFixture({ id: '11111111-1111-1111-1111-111111111111', slug: 'Bad Slug', group: 'other' }),
    pageFixture({ id: '22222222-2222-2222-2222-222222222222', slug: 'second', date: 'not-a-date' }),
    pageFixture({ id: '33333333-3333-3333-3333-333333333333', slug: 'third', date: '2026-02-31' }),
  ], { groupAllowlist: ['tech'] });

  assert.ok(result.errors.length >= 4);
  assert.match(result.errors.join('\n'), /invalid Slug/);
  assert.match(result.errors.join('\n'), /is not allowed/);
  assert.match(result.errors.join('\n'), /invalid date/);
});

test('slug and alias routes must be globally unique', () => {
  const result = validatePublishedPages([
    pageFixture({ id: '11111111-1111-1111-1111-111111111111', slug: 'first', aliases: ['legacy'] }),
    pageFixture({ id: '22222222-2222-2222-2222-222222222222', slug: 'legacy' }),
  ], { groupAllowlist: ['tech'] });
  assert.match(result.errors.join('\n'), /Route "legacy" is claimed by multiple published pages/);
});

test('Markdown text is escaped and unsafe protocols are rejected', () => {
  assert.equal(escapeMarkdownText('<script>*x*</script>'), '&lt;script&gt;\\*x\\*&lt;/script&gt;');
  assert.equal(sanitizeUrl('javascript:alert(1)', new Set(['https:'])), '');
  assert.equal(sanitizeUrl('https://example.com/a', new Set(['https:'])), 'https://example.com/a');

  const context = { unsafeUrlCounts: new Map() };
  const markdown = richTextToMarkdown([{
    plain_text: '<img src=x>',
    href: 'javascript:alert(1)',
    annotations: {},
  }], context);
  assert.equal(markdown, '&lt;img src=x&gt;');
  assert.equal(context.unsafeUrlCounts.get('rich_text_link'), 1);

  const safeContext = { unsafeUrlCounts: new Map() };
  const spacedLink = richTextToMarkdown([{
    plain_text: 'read',
    href: 'https://example.com/a b',
    annotations: {},
  }], safeContext);
  assert.equal(spacedLink, '[read](<https://example.com/a%20b>)');
  assert.throws(() => resolveContentDir('/private/tmp/not-a-project-content-dir'), /Unsafe CONTENT_DIR/);
});

test('Notion image downloads are content-addressed and deduplicated', async () => {
  const mediaStore = { files: new Map(), bySourceUrl: new Map() };
  const bytes = Buffer.from('fake-png');
  let fetchCount = 0;
  const fetchImpl = async () => {
    fetchCount += 1;
    return {
      ok: true,
      status: 200,
      url: 'https://files.example.test/image.png',
      headers: new Headers({ 'content-type': 'image/png', 'content-length': String(bytes.length) }),
      arrayBuffer: async () => bytes,
    };
  };

  const first = await downloadNotionImage('https://files.example.test/image.png', mediaStore, { fetchImpl });
  const second = await downloadNotionImage('https://files.example.test/image.png', mediaStore, { fetchImpl });
  assert.equal(first, second);
  assert.match(first, /^\.\.\/media\/[a-f0-9]{64}\.png$/);
  assert.equal(fetchCount, 1);
  assert.equal(mediaStore.files.size, 1);
});

test('snapshot output replaces old state and emits schemaVersion 1 manifest', async (t) => {
  const temporaryRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'mozhu-content-test-'));
  t.after(() => fs.rmSync(temporaryRoot, { recursive: true, force: true }));
  const outputDir = path.join(temporaryRoot, 'notion');
  fs.mkdirSync(outputDir, { recursive: true });
  fs.writeFileSync(path.join(outputDir, 'stale.txt'), 'stale', 'utf8');

  const client = {
    blocks: {
      children: {
        list: async () => ({
          results: [{
            id: 'block-1',
            type: 'paragraph',
            has_children: false,
            paragraph: { rich_text: richText('<b>safe</b>') },
          }],
          has_more: false,
          next_cursor: null,
        }),
      },
    },
  };
  const validation = validatePublishedPages([pageFixture({ excerpt: '' })], { groupAllowlist: ['tech'] });
  const writebacks = [];
  const snapshot = await buildSnapshot(client, validation.articles, {
    generateSummary: async () => '经过语义理解重写的测试摘要，用于验证生成结果能够被稳定写入文章快照。',
    writeSummary: async (pageId, excerpt) => writebacks.push({ pageId, excerpt }),
  });
  const manifest = createManifest(snapshot);
  writeSnapshot(outputDir, snapshot, manifest);

  assert.equal(fs.existsSync(path.join(outputDir, 'stale.txt')), false);
  assert.equal(manifest.schemaVersion, 1);
  assert.equal(manifest.count, 1);
  assert.equal(snapshot.summaryCount, 1);
  assert.equal(snapshot.summaryWritebackCount, 1);
  assert.equal(writebacks.length, 1);
  assert.equal(manifest.articles[0].path, 'posts/safe-article.md');
  assert.match(fs.readFileSync(path.join(outputDir, 'posts/safe-article.md'), 'utf8'), /&lt;b&gt;safe&lt;\/b&gt;/);
  assert.match(fs.readFileSync(path.join(outputDir, 'posts/safe-article.md'), 'utf8'), /经过语义理解重写/);
  assert.doesNotThrow(() => JSON.parse(fs.readFileSync(path.join(outputDir, 'manifest.json'), 'utf8')));

  const frontmatter = serializeFrontmatter(snapshot.articles[0]);
  assert.match(frontmatter, /notionId:/);
  assert.match(frontmatter, /tags:/);
  assert.match(frontmatter, /cover: ""/);
  assert.match(frontmatter, /aliases: \[\]/);
  assert.match(frontmatter, /updatedAt:/);
});
